# Generated by Django 5.1.4 on 2025-01-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=2)),
                ('phone_no', models.IntegerField()),
                ('amount', models.FloatField()),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
