# Generated by Django 5.1.4 on 2025-01-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transaction',
        ),
    ]
