# Generated by Django 5.1.4 on 2025-01-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('slno', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=2)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
