# Generated by Django 5.1.4 on 2025-01-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_name', models.CharField(max_length=30)),
                ('roi', models.FloatField()),
            ],
        ),
    ]
