# Generated by Django 5.1.4 on 2025-01-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loan',
        ),
    ]
