# Generated by Django 5.1.4 on 2025-01-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0008_customerloan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerLoan',
        ),
    ]
